---
downloads: $SET_ME_UP_HOME/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .osx
  - .vimrc

homebrew_packages:
  - libffi
  - sqlite

  # Do we need any of these?
  - opus
  - pkg-config
  - xkeyboardconfig
  - xvid
  - opusfile

  # CLI tools
  - python-yq
  - jq # dependency of python-yq
  - cmus
  - openssl
  - qrencode
  - fontconfig
  - htop
  - git
  - tree
  - tmux
  - autojump
  - neovim
  - nmap
  - terminal-notifier # CLI notifs
  - noti # CLI notifs
  ## ZSH
  - zsh
  - zsh-syntax-highlighting
  - zsh-history-substring-search

  # MongoDB
  - mongodb-community
  - mongodb-database-tools
  - mongodb-compass-community

  # Programming languages
  - ruby
  - go
  - ghc
  - python
  - node
  ## C
  - gdb
  - gcc
  - ctags
  ## JDK languages
  - openjdk
  - kotlin
  - gradle

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - amethyst
  - android-studio
  - background-music
  - basictex
  - firefox
  - iterm2
  - karabiner-elements
  - postman
  - ukelele
  - visual-studio-code
  - superhuman
  - whatsapp
  - wireshark
  - zoomus
  - google-chrome
  - slack

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_uninstalled_apps:
  - { id: 409183694, name: "Keynote" }
  - { id: 409203825, name: "Numbers" }
  - { id: 682658836, name: "GarageBand" }
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
composer_packages: []
gem_packages: []
npm_packages: []

pip_packages:
  - name: PyYAML
  - name: certifi
  - name: charset-normalizer
  - name: greenlet
  - name: idna
  - name: msgpack
  - name: mutagen
  - name: numpy
  - name: pandas
  - name: python-dateutil
  - name: pytz
  - name: requests
  - name: setuptools
  - name: six
  - name: tqdm
  - name: urllib3
  - name: wheel

  # Neovim
  - name: neovim
  - name: pynvim

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: null
sublime_config_path: null
sublime_package_control: []

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
